---
- name: Radarr Install
  when: radarr_configure == true
  tags:
    - radarr
  block:
    - name: Refresh apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 216000 # seconds; i.e. 1 day

    - name: Gather facts # to determine distribution etc.
      ansible.builtin.setup:

    - include_tasks: user.yml
    - include_tasks: radarr.yml
