---
- name: Start Radarr
  ansible.builtin.systemd:
    name: radarr
    daemon_reload: yes
    enabled: yes
    state: started
  tags:
    # radarr will always stop/start on every run to avoid installing a new
    # version over the existing one while it's running.
    - molecule-idempotence-notest
